//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingAirline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.DoanhThuThangs = new HashSet<DoanhThuThang>();
        }
    
        public string MaHD { get; set; }
        public string MaVe { get; set; }
        public string IDNV { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoanhThuThang> DoanhThuThangs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Ve Ve { get; set; }
    }
}
