//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingAirline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingAirLightEntities : DbContext
    {
        public BookingAirLightEntities()
            : base("name=BookingAirLightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietChuyenBay> ChiTietChuyenBay { get; set; }
        public virtual DbSet<ChiTietHD> ChiTietHD { get; set; }
        public virtual DbSet<ChucVu> ChucVu { get; set; }
        public virtual DbSet<ChuyenBay> ChuyenBay { get; set; }
        public virtual DbSet<DoanhThuNam> DoanhThuNam { get; set; }
        public virtual DbSet<DoanhThuThang> DoanhThuThang { get; set; }
        public virtual DbSet<HangVe> HangVe { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<LoaiKH> LoaiKH { get; set; }
        public virtual DbSet<MayBay> MayBay { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<Phi> Phi { get; set; }
        public virtual DbSet<PhieuDatCho> PhieuDatCho { get; set; }
        public virtual DbSet<SanBay> SanBay { get; set; }
        public virtual DbSet<TuyenBay> TuyenBay { get; set; }
        public virtual DbSet<Ve> Ve { get; set; }
        public virtual DbSet<Voucher> Voucher { get; set; }
        public virtual DbSet<Wishlist> Wishlist { get; set; }
    }
}
