//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingAirline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingAirLightEntities : DbContext
    {
        public BookingAirLightEntities()
            : base("name=BookingAirLightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietChuyenBay> ChiTietChuyenBays { get; set; }
        public virtual DbSet<ChiTietHD> ChiTietHDs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<ChuyenBay> ChuyenBays { get; set; }
        public virtual DbSet<DoanhThuNam> DoanhThuNams { get; set; }
        public virtual DbSet<DoanhThuThang> DoanhThuThangs { get; set; }
        public virtual DbSet<HangVe> HangVes { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiKH> LoaiKHs { get; set; }
        public virtual DbSet<MayBay> MayBays { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<Phi> Phis { get; set; }
        public virtual DbSet<PhieuDatCho> PhieuDatChoes { get; set; }
        public virtual DbSet<SanBay> SanBays { get; set; }
        public virtual DbSet<TuyenBay> TuyenBays { get; set; }
        public virtual DbSet<Ve> Ves { get; set; }
        public virtual DbSet<Wishlist> Wishlists { get; set; }
    }
}
