//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingAirline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        BookingAirLightEntities db = new BookingAirLightEntities();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string MaVC { get; set; }
        public string TenVC { get; set; }
        public Nullable<double> ChietKhau { get; set; }
        public Nullable<System.DateTime> NgayApDung { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDon { get; set; }
        public bool Update(Voucher vc)
        {
            try
            {
                var voucher = db.Voucher.Find(vc.MaVC);
                voucher.MaVC = vc.MaVC;
                voucher.TenVC = vc.TenVC;
                voucher.ChietKhau = vc.ChietKhau;
                voucher.NgayApDung = vc.NgayApDung;
                voucher.NgayHetHan = vc.NgayHetHan;
                voucher.TinhTrang = vc.TinhTrang;
                db.SaveChanges();
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }

        }
        public Voucher ViewDetail(string id)
        {
            return db.Voucher.Find(id);
        }
    }
}
